// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://visyatriuaswwbhvtgic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpc3lhdHJpdWFzd3diaHZ0Z2ljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY5ODE1NzMsImV4cCI6MjA5MjU1NzU3M30.P29eR4DxIehzynJ2pdkToHSYTB-sbY7yuXlZz65jlpg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});